output_folder: "pandora_output_small_heavy_only"
original_prg: "sample_data/prgs/prg.fa"

coverages:
  - 10

subsamplings:
  - random

technologies:
  - illumina
  - nanopore

samples: metadata/samples_small.csv
subsampled_reads_dir: metadata/subsampled_reads_small.csv

msas_dir: sample_data/msas
msas_csv: metadata/msas_small.csv

complex_MSA_sequence_threshold: 1

containers:
  conda: "docker://continuumio/miniconda3:4.7.12"
  pandora: docker://leandroishilima/pandora_analysis_pipeline:pandora_paper_tag1
  make_prg: docker://leandroishilima/make_prg:c61d9b
