output_folder: "pandora_output_small"

coverages:
  - 10

subsamplings:
  - random

technologies:
  - illumina
  - nanopore

samples: metadata/samples_small.csv
subsampled_reads_dir: metadata/subsampled_reads_small.csv

msas_dir: sample_data/msas

pandora_URL: "https://github.com/rmcolq/pandora/releases/download/pandora_paper_tag1/pandora-linux-precompiled-pandora_paper_tag1.gz"
make_prg_URL: "https://github.com/leoisl/make_prg/releases/download/v0.2.0_prototype/make_prg_0.2.0_prototype"
containers:
  mafft: docker://leandroishilima/pandora_workflow_mafft:latest
